<?php
declare(strict_types=1);

require_once __DIR__ . '/../app/push_campaigns.php';
proteger_admin();
$pdo=getPDO();push_campaigns_ensure_schema($pdo);
$canWrite=($_SESSION['admin_tipo']??'principal')!=='equipe';if(!$canWrite){$perms=json_decode((string)($_SESSION['equipe_perms']??''),true)?:[];$canWrite=!empty($perms['notificacoes']['escrever']);}
if(empty($_SESSION['push_campaign_csrf']))$_SESSION['push_campaign_csrf']=bin2hex(random_bytes(24));$csrf=(string)$_SESSION['push_campaign_csrf'];
function pc_h($v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function pc_status_label(string $status):string{return [
    'draft'=>'Rascunho','queued'=>'Na fila','scheduled'=>'Agendado','processing'=>'Processando',
    'paused'=>'Pausado','completed'=>'Concluído','failed'=>'Com erro','cancelled'=>'Cancelado',
    'running'=>'Em andamento','enqueued'=>'Enfileirado','error'=>'Erro','retry'=>'Nova tentativa',
    'accepted'=>'Aceito pelo Firebase','clicked'=>'Clicado','skipped'=>'Ignorado',
][$status]??ucfirst(str_replace('_',' ',$status));}
$message='';$error='';

if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        if(!$canWrite)throw new RuntimeException('Sem permissão de escrita.');if(!hash_equals($csrf,(string)($_POST['csrf']??'')))throw new RuntimeException('Sessão expirada.');$action=(string)($_POST['action']??'');
        if($action==='create'){
            $filters=['search'=>$_POST['filter_search']??'','turma'=>$_POST['filter_turma']??'','tag'=>$_POST['filter_tag']??'','progress'=>$_POST['filter_progress']??'all','only_push_enabled'=>isset($_POST['only_push_enabled'])];
            $id=push_campaign_create($pdo,['name'=>$_POST['name']??'','dispatch_type'=>$_POST['dispatch_type']??'instant','scheduled_at'=>$_POST['scheduled_at']??'','flow_ids'=>$_POST['flow_ids']??[],'filters'=>$filters],(string)($_SESSION['equipe_nome']??'Administrador'));
            header('Location: push_campanhas.php?created='.$id);exit;
        }
        $id=max(0,(int)($_POST['campaign_id']??0));if($id<=0)throw new InvalidArgumentException('Campanha inválida.');
        if($action==='pause')$pdo->prepare("UPDATE push_campaigns SET status='paused' WHERE id=:id AND status IN ('queued','scheduled','processing')")->execute(['id'=>$id]);
        elseif($action==='resume')$pdo->prepare("UPDATE push_campaigns SET status=IF(scheduled_at IS NOT NULL AND scheduled_at>NOW(),'scheduled','queued') WHERE id=:id AND status='paused'")->execute(['id'=>$id]);
        elseif($action==='cancel'){$pdo->prepare("UPDATE push_campaigns SET status='cancelled',finished_at=NOW() WHERE id=:id AND status NOT IN ('completed','cancelled')")->execute(['id'=>$id]);$pdo->prepare("UPDATE push_campaign_recipients SET status='cancelled' WHERE campaign_id=:id AND status='queued'")->execute(['id'=>$id]);}
        elseif($action==='delete'){$st=$pdo->prepare("SELECT status FROM push_campaigns WHERE id=:id");$st->execute(['id'=>$id]);$status=(string)$st->fetchColumn();if(!in_array($status,['completed','cancelled','failed'],true))throw new RuntimeException('Pause e cancele a campanha antes de excluir.');$pdo->beginTransaction();$pdo->prepare('DELETE FROM push_campaign_executions WHERE campaign_id=:id')->execute(['id'=>$id]);$pdo->prepare('DELETE FROM push_campaign_recipients WHERE campaign_id=:id')->execute(['id'=>$id]);$pdo->prepare('DELETE FROM push_campaign_flows WHERE campaign_id=:id')->execute(['id'=>$id]);$pdo->prepare('DELETE FROM push_campaigns WHERE id=:id')->execute(['id'=>$id]);$pdo->commit();}
        header('Location: push_campanhas.php?updated=1');exit;
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
}

if(isset($_GET['preview'])){header('Content-Type: application/json; charset=utf-8');try{$filters=['search'=>$_GET['search']??'','turma'=>$_GET['turma']??'','tag'=>$_GET['tag']??'','progress'=>$_GET['progress']??'all','only_push_enabled'=>(string)($_GET['push']??'1')==='1'];echo json_encode(['ok'=>true]+push_campaign_preview($pdo,$filters,20),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}catch(Throwable $e){http_response_code(400);echo json_encode(['ok'=>false,'error'=>$e->getMessage()],JSON_UNESCAPED_UNICODE);}exit;}
if(!empty($_GET['created']))$message='Campanha criada e audiência congelada.';elseif(!empty($_GET['updated']))$message='Campanha atualizada.';

$flows=$pdo->query("SELECT f.id,f.name,f.status,v.version_number,v.graph_json FROM push_flows f JOIN push_flow_versions v ON v.id=f.current_version_id WHERE f.status IN ('active','paused') ORDER BY f.name")->fetchAll(PDO::FETCH_ASSOC)?:[];
foreach($flows as &$flow){$actions=[];try{$graph=push_flow_decode_graph((string)$flow['graph_json']);foreach($graph['nodes']??[] as $node){$type=(string)($node['type']??'');if($type==='trigger')continue;$actions[]=trim((string)($node['config']['label']??''))?:$type;}}catch(Throwable $e){}$flow['actions']=array_values(array_unique($actions));}unset($flow);
$turmas=$pdo->query("SELECT codigo,codigo nome FROM turmas ORDER BY codigo DESC")->fetchAll(PDO::FETCH_ASSOC)?:[];$tags=$pdo->query("SELECT nome FROM tags WHERE ativo=1 ORDER BY nome")->fetchAll(PDO::FETCH_COLUMN)?:[];
$campaigns=$pdo->query("SELECT c.*,
    (SELECT GROUP_CONCAT(CONCAT(cf.flow_name,' v',cf.version_number) ORDER BY cf.id SEPARATOR ', ') FROM push_campaign_flows cf WHERE cf.campaign_id=c.id) flow_names,
    (SELECT COUNT(*) FROM push_campaign_executions ce WHERE ce.campaign_id=c.id AND ce.status IN ('queued','running')) active_runs,
    (SELECT COUNT(*) FROM push_campaign_recipients cr WHERE cr.campaign_id=c.id AND cr.status='error') recipient_errors,
    (SELECT COUNT(*) FROM push_delivery_logs dl JOIN push_notifications n ON n.id=dl.notification_id JOIN push_flow_jobs j ON n.target_type='flow_job' AND n.target_value=CONCAT('flow_job:',j.id) JOIN push_campaign_executions ce ON ce.run_id=j.run_id WHERE ce.campaign_id=c.id AND dl.status IN ('accepted','clicked')) accepted_devices,
    (SELECT COUNT(*) FROM push_delivery_logs dl JOIN push_notifications n ON n.id=dl.notification_id JOIN push_flow_jobs j ON n.target_type='flow_job' AND n.target_value=CONCAT('flow_job:',j.id) JOIN push_campaign_executions ce ON ce.run_id=j.run_id WHERE ce.campaign_id=c.id AND dl.status IN ('failed','uninstalled')) delivery_errors,
    (SELECT COUNT(*) FROM push_delivery_logs dl JOIN push_notifications n ON n.id=dl.notification_id JOIN push_flow_jobs j ON n.target_type='flow_job' AND n.target_value=CONCAT('flow_job:',j.id) JOIN push_campaign_executions ce ON ce.run_id=j.run_id WHERE ce.campaign_id=c.id AND dl.clicked_at IS NOT NULL) clicks
    FROM push_campaigns c ORDER BY c.id DESC LIMIT 100")->fetchAll(PDO::FETCH_ASSOC)?:[];
$detailId=max(0,(int)($_GET['id']??0));$details=[];$detailCampaign=null;
if($detailId>0){$st=$pdo->prepare('SELECT * FROM push_campaigns WHERE id=:id');$st->execute(['id'=>$detailId]);$detailCampaign=$st->fetch(PDO::FETCH_ASSOC)?:null;$st=$pdo->prepare("SELECT cr.id recipient_id,cr.status recipient_status,cr.error_message recipient_error,u.nome,u.email,u.codigo_turma,cf.flow_name,cf.version_number,ce.status execution_status,ce.error_message execution_error,r.id run_id,r.status run_status,
    (SELECT j.node_id FROM push_flow_jobs j WHERE j.run_id=r.id ORDER BY j.id DESC LIMIT 1) current_node,
    (SELECT j.status FROM push_flow_jobs j WHERE j.run_id=r.id ORDER BY j.id DESC LIMIT 1) current_job_status,v.graph_json
    FROM push_campaign_recipients cr JOIN users u ON u.id=cr.user_id LEFT JOIN push_campaign_executions ce ON ce.recipient_id=cr.id LEFT JOIN push_campaign_flows cf ON cf.flow_id=ce.flow_id AND cf.version_id=ce.version_id AND cf.campaign_id=cr.campaign_id LEFT JOIN push_flow_runs r ON r.id=ce.run_id LEFT JOIN push_flow_versions v ON v.id=ce.version_id WHERE cr.campaign_id=:id ORDER BY cr.id DESC,cf.id LIMIT 1000");$st->execute(['id'=>$detailId]);$details=$st->fetchAll(PDO::FETCH_ASSOC)?:[];foreach($details as &$detail){$nodeId=(string)($detail['current_node']??'');if($nodeId!==''){try{$graph=push_flow_decode_graph((string)($detail['graph_json']??''));foreach($graph['nodes']??[] as $node){if((string)($node['id']??'')===$nodeId){$detail['current_node']=trim((string)($node['config']['label']??''))?:(string)($node['type']??$nodeId);break;}}}catch(Throwable $e){}}}unset($detail);}
$menu='notificacoes';$page_title='Campanhas Push';include __DIR__.'/_header.php';
?>
<style>
.pc{display:grid;gap:16px}.pc-card{background:var(--bg-card);border:1px solid var(--border);border-radius:14px;padding:16px}.pc-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.pc-head h1,.pc-card h2{margin:0}.pc-sub{color:var(--muted);font-size:11px;margin-top:4px}.pc-form{display:grid;gap:13px}.pc-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.pc-field label{display:block;color:var(--muted);font-size:10px;text-transform:uppercase;margin-bottom:5px}.pc-field input,.pc-field select{width:100%;padding:9px;border:1px solid var(--border);border-radius:8px;background:var(--bg);color:var(--text)}.pc-flows{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.pc-flow{display:flex;gap:9px;padding:11px;border:1px solid var(--border);border-radius:9px;background:var(--bg)}.pc-flow input{margin-top:2px}.pc-flow strong,.pc-flow span{display:block}.pc-flow span{font-size:10px;color:var(--muted);margin-top:3px}.pc-preview{padding:12px;border:1px dashed var(--border);border-radius:9px;color:var(--muted);font-size:12px}.pc-list{display:grid;gap:9px}.pc-row{border:1px solid var(--border);border-radius:11px;background:var(--bg);padding:13px}.pc-row-main{display:grid;grid-template-columns:minmax(180px,1fr) 110px minmax(190px,1fr) auto;gap:12px;align-items:center}.pc-metrics{display:flex;gap:15px;flex-wrap:wrap;margin-top:10px}.pc-metric strong,.pc-metric span{display:block}.pc-metric strong{font-size:16px}.pc-metric span{font-size:9px;color:var(--muted);text-transform:uppercase}.pc-actions{display:flex;gap:6px;flex-wrap:wrap}.pc-status{display:inline-flex;padding:4px 8px;border-radius:99px;background:var(--bg-hover);font-size:10px;text-transform:uppercase}.pc-status.completed{background:var(--success-dim);color:#86efac}.pc-status.processing,.pc-status.queued,.pc-status.scheduled{background:var(--warning-dim);color:#fcd34d}.pc-status.failed,.pc-status.cancelled{background:var(--danger-dim);color:#fca5a5}.pc-table{overflow:auto}.pc-table table{min-width:900px}.pc-alert{padding:11px;border-radius:9px}.pc-ok{background:var(--success-dim);color:#86efac}.pc-error{background:var(--danger-dim);color:#fca5a5}@media(max-width:800px){.pc-grid,.pc-flows{grid-template-columns:1fr}.pc-row-main{grid-template-columns:1fr}}
</style>
<div class="pc">
<?php if($message):?><div class="pc-alert pc-ok"><?=pc_h($message)?></div><?php endif;?><?php if($error):?><div class="pc-alert pc-error"><?=pc_h($error)?></div><?php endif;?>
<div class="pc-head"><div><h1>Campanhas Push</h1><div class="pc-sub">Dispare fluxos publicados para uma audiência filtrada, agora ou em horário agendado.</div></div><a class="btn btn-ghost" href="notificacoes.php">← Notificações</a></div>
<section class="pc-card"><h2>Nova campanha</h2><div class="pc-sub" style="margin-bottom:14px">A audiência é congelada ao criar. Todos os blocos dos fluxos selecionados serão executados, inclusive tags e integrações.</div>
<form method="post" class="pc-form" id="pcForm"><input type="hidden" name="csrf" value="<?=pc_h($csrf)?>"><input type="hidden" name="action" value="create">
<div class="pc-grid"><div class="pc-field"><label>Nome da campanha</label><input name="name" maxlength="180" required></div><div class="pc-field"><label>Execução</label><select name="dispatch_type" id="pcType"><option value="instant">Imediata</option><option value="scheduled">Agendada</option></select></div><div class="pc-field" id="pcSchedule" hidden><label>Data e hora</label><input type="datetime-local" name="scheduled_at"></div><div class="pc-field"><label>Busca por nome, e-mail ou telefone</label><input name="filter_search" id="pcSearch"></div><div class="pc-field"><label>Turma</label><select name="filter_turma" id="pcTurma"><option value="">Todas</option><?php foreach($turmas as $t):?><option value="<?=pc_h($t['codigo'])?>"><?=pc_h($t['codigo'].' · '.$t['nome'])?></option><?php endforeach;?></select></div><div class="pc-field"><label>Tag</label><select name="filter_tag" id="pcTag"><option value="">Todas</option><?php foreach($tags as $tag):?><option value="<?=pc_h($tag)?>"><?=pc_h($tag)?></option><?php endforeach;?></select></div><div class="pc-field"><label>Progresso</label><select name="filter_progress" id="pcProgress"><option value="all">Qualquer progresso</option><option value="no_lesson">Não viu nenhuma aula</option><option value="any_lesson">Viu alguma aula</option><option value="completed_trail">Concluiu a trilha</option></select></div><div class="pc-field"><label>Elegibilidade</label><label style="display:flex;gap:8px;align-items:center;text-transform:none"><input type="checkbox" name="only_push_enabled" id="pcPush" checked style="width:auto"> Somente alunos com push autorizado</label></div></div>
<div><strong style="font-size:12px">Fluxos publicados</strong><div class="pc-flows" style="margin-top:8px"><?php foreach($flows as $flow):?><label class="pc-flow"><input type="checkbox" name="flow_ids[]" value="<?=(int)$flow['id']?>"><span><strong><?=pc_h($flow['name'].' · v'.$flow['version_number'].($flow['status']==='paused'?' · pausado':''))?></strong><span><?=pc_h($flow['actions']?implode(' → ',$flow['actions']):'Fluxo sem ações após o gatilho')?></span></span></label><?php endforeach;?><?php if(!$flows):?><div class="pc-preview">Não há fluxos com versão publicada.</div><?php endif;?></div></div>
<div class="pc-preview" id="pcPreview">A prévia da audiência aparecerá aqui.</div><div><button class="btn btn-primary" type="submit" <?=$canWrite&&$flows?'':'disabled'?>>Criar e enfileirar campanha</button></div></form></section>
<section class="pc-card"><h2>Campanhas</h2><div class="pc-list" style="margin-top:12px"><?php foreach($campaigns as $c):?><div class="pc-row"><div class="pc-row-main"><div><strong><?=pc_h($c['name'])?></strong><div class="pc-sub"><?=pc_h($c['flow_names']??'')?> · <?=!empty($c['scheduled_at'])?'agendada para '.pc_h(date('d/m/Y H:i',strtotime($c['scheduled_at']))):'criada em '.pc_h(date('d/m/Y H:i',strtotime($c['created_at'])))?></div></div><div><span class="pc-status <?=pc_h($c['status'])?>"><?=pc_h(pc_status_label((string)$c['status']))?></span></div><div class="pc-metrics"><div class="pc-metric"><strong><?=(int)$c['total_recipients']?></strong><span>Selecionados</span></div><div class="pc-metric"><strong><?=(int)$c['eligible_recipients']?></strong><span>Com push</span></div><div class="pc-metric"><strong><?=(int)$c['completed_runs']?></strong><span>Concluídos</span></div><div class="pc-metric"><strong><?=(int)$c['active_runs']?></strong><span>Em andamento</span></div><div class="pc-metric"><strong><?=((int)$c['failed_runs']+(int)$c['recipient_errors'])?></strong><span>Erros fluxo</span></div><div class="pc-metric"><strong><?=(int)$c['accepted_devices']?></strong><span>Firebase</span></div><div class="pc-metric"><strong><?=(int)$c['delivery_errors']?></strong><span>Erros entrega</span></div><div class="pc-metric"><strong><?=(int)$c['clicks']?></strong><span>Cliques</span></div></div><div class="pc-actions"><a class="btn btn-ghost btn-xs" href="?id=<?=(int)$c['id']?>">Detalhes</a><?php if($canWrite&&in_array($c['status'],['queued','scheduled','processing'],true)):?><form method="post"><input type="hidden" name="csrf" value="<?=pc_h($csrf)?>"><input type="hidden" name="campaign_id" value="<?=(int)$c['id']?>"><button class="btn btn-ghost btn-xs" name="action" value="pause">Pausar</button><button class="btn btn-danger btn-xs" name="action" value="cancel" onclick="return confirm('Cancelar entradas ainda não iniciadas?')">Cancelar</button></form><?php elseif($canWrite&&$c['status']==='paused'):?><form method="post"><input type="hidden" name="csrf" value="<?=pc_h($csrf)?>"><input type="hidden" name="campaign_id" value="<?=(int)$c['id']?>"><button class="btn btn-primary btn-xs" name="action" value="resume">Retomar</button><button class="btn btn-danger btn-xs" name="action" value="cancel">Cancelar</button></form><?php endif;?></div></div></div><?php endforeach;?><?php if(!$campaigns):?><div class="pc-preview">Nenhuma campanha criada.</div><?php endif;?></div></section>
<?php if($detailCampaign):?><section class="pc-card"><div class="pc-head"><div><h2><?=pc_h($detailCampaign['name'])?></h2><div class="pc-sub">Lista congelada de destinatários e andamento por fluxo.</div></div><div class="pc-grid" style="min-width:min(440px,100%)"><div class="pc-field"><label>Filtrar nome/e-mail</label><input id="pcDetailName"></div><div class="pc-field"><label>Filtrar turma</label><input id="pcDetailTurma"></div></div></div><div class="pc-table" style="margin-top:12px"><table><thead><tr><th>Aluno</th><th>Turma</th><th>Fluxo</th><th>Status</th><th>Bloco atual</th><th>Erro</th></tr></thead><tbody><?php foreach($details as $d):?><?php $detailStatus=(string)($d['run_status']??$d['recipient_status']);?><tr class="pc-detail-row" data-name="<?=pc_h(mb_strtolower(($d['nome']??'').' '.($d['email']??'')))?>" data-turma="<?=pc_h(mb_strtolower((string)($d['codigo_turma']??'')))?>"><td><strong><?=pc_h($d['nome'])?></strong><div class="pc-sub"><?=pc_h($d['email'])?></div></td><td><?=pc_h($d['codigo_turma'])?></td><td><?=pc_h(($d['flow_name']??'Aguardando').' '.(!empty($d['version_number'])?'v'.$d['version_number']:''))?></td><td><span class="pc-status <?=pc_h($detailStatus)?>"><?=pc_h(pc_status_label($detailStatus))?></span></td><td><?=pc_h(($d['run_status']??'')==='completed'?'Fluxo concluído':($d['current_node']?:'Aguardando entrada'))?></td><td><?=pc_h($d['execution_error']??$d['recipient_error']??'')?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
</div>
<script>
(()=>{const type=document.getElementById('pcType'),schedule=document.getElementById('pcSchedule');type.addEventListener('change',()=>schedule.hidden=type.value!=='scheduled');const fields=['pcSearch','pcTurma','pcTag','pcProgress','pcPush'].map(id=>document.getElementById(id)),preview=document.getElementById('pcPreview');let timer;async function loadPreview(){clearTimeout(timer);timer=setTimeout(async()=>{const q=new URLSearchParams({preview:'1',search:fields[0].value,turma:fields[1].value,tag:fields[2].value,progress:fields[3].value,push:fields[4].checked?'1':'0'});preview.textContent='Calculando audiência...';try{const r=await fetch('push_campanhas.php?'+q,{credentials:'same-origin'}),d=await r.json();preview.innerHTML=d.ok?'<strong>'+d.total+' aluno(s)</strong> correspondem aos filtros. A lista será congelada ao criar a campanha.':d.error}catch(e){preview.textContent='Não foi possível calcular a audiência.'}},300)}fields.forEach(f=>f.addEventListener(f.type==='checkbox'?'change':'input',loadPreview));loadPreview();const dn=document.getElementById('pcDetailName'),dt=document.getElementById('pcDetailTurma');function filter(){const n=(dn.value||'').toLocaleLowerCase('pt-BR'),t=(dt.value||'').toLocaleLowerCase('pt-BR');document.querySelectorAll('.pc-detail-row').forEach(r=>r.hidden=!!((n&&!r.dataset.name.includes(n))||(t&&!r.dataset.turma.includes(t))))}if(dn&&dt){dn.addEventListener('input',filter);dt.addEventListener('input',filter)}})();
</script>
<?php include __DIR__.'/_footer.php'; ?>
